In [24]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sklearn.metrics import mean_squared_error, r2_score

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor

## **Data Loading**

In [2]:
df = pd.read_csv(r"C:\Users\ASUS\Desktop\Sem04\Coding\sem04_Codes\UOM_sem_04\Inputs\Accident\train.csv")
df_test = pd.read_csv(r"C:\Users\ASUS\Desktop\Sem04\Coding\sem04_Codes\UOM_sem_04\Inputs\Accident\test.csv")

In [3]:
print(df.shape)
print(df_test.shape)

(517754, 14)
(172585, 13)

In [4]:
df.describe()

,id,num_lanes,curvature,speed_limit,num_reported_accidents,accident_risk
count,517754.000000,517754.000000,517754.000000,517754.000000,517754.000000,517754.000000
mean,258876.500000,2.491511,0.488719,46.112575,1.187970,0.352377
std,149462.849975,1.120434,0.272563,15.788521,0.895961,0.166417
min,0.000000,1.000000,0.000000,25.000000,0.000000,0.000000
25%,129438.250000,1.000000,0.260000,35.000000,1.000000,0.230000
50%,258876.500000,2.000000,0.510000,45.000000,1.000000,0.340000
75%,388314.750000,3.000000,0.710000,60.000000,2.000000,0.460000
max,517753.000000,4.000000,1.000000,70.000000,7.000000,1.000000

In [5]:
df.head()

,id,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents,accident_risk
0,0,urban,2,0.06,35,daylight,rainy,False,True,afternoon,False,True,1,0.13
1,1,urban,4,0.99,35,daylight,clear,True,False,evening,True,True,0,0.35
2,2,rural,4,0.63,70,dim,clear,False,True,morning,True,False,2,0.30
3,3,highway,4,0.07,35,dim,rainy,True,True,morning,False,False,1,0.21
4,4,rural,1,0.58,60,daylight,foggy,False,False,evening,True,False,1,0.56

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 517754 entries, 0 to 517753
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      517754 non-null  int64
 1   road_type               517754 non-null  str
 2   num_lanes               517754 non-null  int64
 3   curvature               517754 non-null  float64
 4   speed_limit             517754 non-null  int64
 5   lighting                517754 non-null  str
 6   weather                 517754 non-null  str
 7   road_signs_present      517754 non-null  bool
 8   public_road             517754 non-null  bool
 9   time_of_day             517754 non-null  str
 10  holiday                 517754 non-null  bool
 11  school_season           517754 non-null  bool
 12  num_reported_accidents  517754 non-null  int64
 13  accident_risk           517754 non-null  float64
dtypes: bool(4), float64(2), int64(4), str(4)
memory usage: 41.5 MB

In [7]:
print(f"Missing Values in Train = {df.isnull().sum()}")
print(f"Missing Values in Test = {df_test.isnull().sum()}")

Missing Values in Train = id                        0
road_type                 0
num_lanes                 0
curvature                 0
speed_limit               0
lighting                  0
weather                   0
road_signs_present        0
public_road               0
time_of_day               0
holiday                   0
school_season             0
num_reported_accidents    0
accident_risk             0
dtype: int64
Missing Values in Test = id                        0
road_type                 0
num_lanes                 0
curvature                 0
speed_limit               0
lighting                  0
weather                   0
road_signs_present        0
public_road               0
time_of_day               0
holiday                   0
school_season             0
num_reported_accidents    0
dtype: int64

## **Data Pre-processing**

In [8]:
# df = pd.get_dummies(df, drop_first=True)

In [9]:
# corr = df.corr()["accident_risk"].abs().sort_values(ascending=False)
# selected_features = corr[corr > 0.3].index

corr

NameError: name 'corr' is not defined

In [10]:
# --- Drop the unwanted colunms ---

drop_cols = ["road_signs_present", "id", "school_season", "num_lanes", "time_of_day"]

for col in drop_cols:
    if col in df: df = df.drop(col, axis=1)
    if col in df_test: df_test = df_test.drop(col, axis=1)

In [11]:
# --- Seperate Target from Features ---

X = df.drop("accident_risk", axis=1)
y = df["accident_risk"]

X_test = df_test.copy()

print(f"Features : {X.columns.to_list()}")
print(f"Target : accident_risk")

Features : ['road_type', 'curvature', 'speed_limit', 'lighting', 'weather', 'public_road', 'holiday', 'num_reported_accidents']
Target : accident_risk

### **Impute Missing Values**

In [12]:
# --- Impute missing values ---

num_cols = X.select_dtypes(include=["number"]).columns
cat_cols = X.select_dtypes(include=["object"]).columns

num_imputer = SimpleImputer(strategy="median")
cat_imputer = SimpleImputer(strategy="most_frequent")

X[num_cols] = num_imputer.fit_transform(X[num_cols])
X_test[num_cols] = num_imputer.transform(X_test[num_cols])

if len(cat_cols):
    X[cat_cols] = cat_imputer.fit_transform(X[cat_cols])
    X_test[cat_cols] = cat_imputer.transform(X_test[cat_cols])

C:\Users\ASUS\AppData\Local\Temp\ipykernel_31676\4092527658.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = X.select_dtypes(include=["object"]).columns

### **Encoding**

In [13]:
# --- 1. One-hot Encoding ---

cat_cols_list = cat_cols.to_list()

if len(cat_cols_list)>0:
    X = pd.get_dummies(X, columns=cat_cols_list, drop_first=False)
    X_test = pd.get_dummies(X_test, columns=cat_cols_list, drop_first=False)

    X, X_test = X.align(X_test, join="left", axis=1, fill_value=0)

### **Scaling**

only when KNN, SVM

In [14]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)
X_test_scaled = scaler.transform(X_test)

In [15]:
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train_sc, X_val_sc, _, _ = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

## **Model Training**

In [16]:
models = {
    "Linear Regression" : LinearRegression(),
    "KNN Regressor" : KNeighborsRegressor(),
    "Decision Tree Regressor" : DecisionTreeRegressor(),
    "Random Forest Regressor" : RandomForestRegressor(),
    "Gradient Boosting reg" : GradientBoostingRegressor(),
    "XGBoost" : XGBRegressor(),
    "CatBoost" : CatBoostRegressor()
}

results = {}

for name, model in models.items():
    if name == "KNN Regressor":
        model.fit(X_train_sc, y_train)
        y_pred = model.predict(X_val_sc)
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_val)

    rmse = np.sqrt(mean_squared_error(y_val, y_pred))
    r2 = r2_score(y_val, y_pred)
    results[name] = r2
    print(f"{name:<30} RMSE: {rmse:.4f}  R²: {r2:.4f}")

best_model_name = max(results, key=results.get)
print(f"Best Model Name : {best_model_name}")

Linear Regression              RMSE: 0.0735  R²: 0.8041
KNN Regressor                  RMSE: 0.0619  R²: 0.8610
Decision Tree Regressor        RMSE: 0.0682  R²: 0.8318
Random Forest Regressor        RMSE: 0.0634  R²: 0.8546
Gradient Boosting reg          RMSE: 0.0570  R²: 0.8823
XGBoost                        RMSE: 0.0563  R²: 0.8852
Learning rate set to 0.106096
0:	learn: 0.1515881	total: 144ms	remaining: 2m 24s
1:	learn: 0.1385273	total: 174ms	remaining: 1m 26s
2:	learn: 0.1270156	total: 201ms	remaining: 1m 6s
3:	learn: 0.1169574	total: 231ms	remaining: 57.5s
4:	learn: 0.1081775	total: 260ms	remaining: 51.7s
5:	learn: 0.1005641	total: 290ms	remaining: 48s
6:	learn: 0.0937216	total: 325ms	remaining: 46.1s
7:	learn: 0.0878705	total: 369ms	remaining: 45.7s
8:	learn: 0.0828767	total: 401ms	remaining: 44.2s
9:	learn: 0.0786609	total: 430ms	remaining: 42.6s
10:	learn: 0.0750360	total: 462ms	remaining: 41.5s
11:	learn: 0.0719753	total: 491ms	remaining: 40.4s
12:	learn: 0.0693934	total: 528ms	remaining: 40.1s
13:	learn: 0.0672678	total: 559ms	remaining: 39.4s
14:	learn: 0.0654566	total: 591ms	remaining: 38.8s
15:	learn: 0.0639765	total: 620ms	remaining: 38.1s
16:	learn: 0.0627175	total: 648ms	remaining: 37.4s
17:	learn: 0.0616785	total: 679ms	remaining: 37s
18:	learn: 0.0608294	total: 711ms	remaining: 36.7s
19:	learn: 0.0601174	total: 741ms	remaining: 36.3s
20:	learn: 0.0595513	total: 770ms	remaining: 35.9s
21:	learn: 0.0590644	total: 799ms	remaining: 35.5s
22:	learn: 0.0586728	total: 831ms	remaining: 35.3s
23:	learn: 0.0583527	total: 860ms	remaining: 35s
24:	learn: 0.0580798	total: 891ms	remaining: 34.8s
25:	learn: 0.0578590	total: 920ms	remaining: 34.5s
26:	learn: 0.0576787	total: 947ms	remaining: 34.1s
27:	learn: 0.0575330	total: 976ms	remaining: 33.9s
28:	learn: 0.0574054	total: 1.01s	remaining: 33.7s
29:	learn: 0.0573039	total: 1.04s	remaining: 33.5s
30:	learn: 0.0572149	total: 1.06s	remaining: 33.2s
31:	learn: 0.0571433	total: 1.09s	remaining: 33.1s
32:	learn: 0.0570763	total: 1.13s	remaining: 33s
33:	learn: 0.0570185	total: 1.16s	remaining: 32.8s
34:	learn: 0.0569700	total: 1.19s	remaining: 32.7s
35:	learn: 0.0569265	total: 1.21s	remaining: 32.5s
36:	learn: 0.0568930	total: 1.24s	remaining: 32.4s
37:	learn: 0.0568587	total: 1.27s	remaining: 32.3s
38:	learn: 0.0568335	total: 1.3s	remaining: 32.1s
39:	learn: 0.0567995	total: 1.33s	remaining: 32s
40:	learn: 0.0567775	total: 1.37s	remaining: 32s
41:	learn: 0.0567553	total: 1.4s	remaining: 31.9s
42:	learn: 0.0567358	total: 1.43s	remaining: 31.8s
43:	learn: 0.0567209	total: 1.46s	remaining: 31.6s
44:	learn: 0.0566971	total: 1.49s	remaining: 31.6s
45:	learn: 0.0566788	total: 1.52s	remaining: 31.6s
46:	learn: 0.0566642	total: 1.55s	remaining: 31.5s
47:	learn: 0.0566498	total: 1.58s	remaining: 31.4s
48:	learn: 0.0566404	total: 1.61s	remaining: 31.3s
49:	learn: 0.0566306	total: 1.64s	remaining: 31.1s
50:	learn: 0.0566163	total: 1.67s	remaining: 31.1s
51:	learn: 0.0566082	total: 1.7s	remaining: 31s
52:	learn: 0.0565950	total: 1.73s	remaining: 30.9s
53:	learn: 0.0565849	total: 1.76s	remaining: 30.8s
54:	learn: 0.0565773	total: 1.79s	remaining: 30.7s
55:	learn: 0.0565652	total: 1.82s	remaining: 30.7s
56:	learn: 0.0565602	total: 1.85s	remaining: 30.5s
57:	learn: 0.0565529	total: 1.88s	remaining: 30.5s
58:	learn: 0.0565443	total: 1.9s	remaining: 30.4s
59:	learn: 0.0565396	total: 1.94s	remaining: 30.4s
60:	learn: 0.0565321	total: 1.97s	remaining: 30.3s
61:	learn: 0.0565240	total: 1.99s	remaining: 30.2s
62:	learn: 0.0565156	total: 2.02s	remaining: 30.1s
63:	learn: 0.0565100	total: 2.05s	remaining: 30s
64:	learn: 0.0565063	total: 2.08s	remaining: 30s
65:	learn: 0.0564965	total: 2.11s	remaining: 29.9s
66:	learn: 0.0564919	total: 2.15s	remaining: 29.9s
67:	learn: 0.0564830	total: 2.17s	remaining: 29.8s
68:	learn: 0.0564788	total: 2.2s	remaining: 29.7s
69:	learn: 0.0564710	total: 2.23s	remaining: 29.7s
70:	learn: 0.0564667	total: 2.26s	remaining: 29.6s
71:	learn: 0.0564566	total: 2.29s	remaining: 29.5s
72:	learn: 0.0564508	total: 2.32s	remaining: 29.5s
73:	learn: 0.0564462	total: 2.35s	remaining: 29.4s
74:	learn: 0.0564426	total: 2.38s	remaining: 29.4s
75:	learn: 0.0564397	total: 2.41s	remaining: 29.3s
76:	learn: 0.0564344	total: 2.44s	remaining: 29.3s
77:	learn: 0.0564297	total: 2.47s	remaining: 29.2s
78:	learn: 0.0564266	total: 2.5s	remaining: 29.2s
79:	learn: 0.0564232	total: 2.54s	remaining: 29.2s
80:	learn: 0.0564216	total: 2.58s	remaining: 29.2s
81:	learn: 0.0564158	total: 2.61s	remaining: 29.2s
82:	learn: 0.0564104	total: 2.64s	remaining: 29.2s
83:	learn: 0.0564084	total: 2.67s	remaining: 29.1s
84:	learn: 0.0564051	total: 2.7s	remaining: 29.1s
85:	learn: 0.0563999	total: 2.73s	remaining: 29s
86:	learn: 0.0563954	total: 2.76s	remaining: 29s
87:	learn: 0.0563914	total: 2.79s	remaining: 28.9s
88:	learn: 0.0563887	total: 2.82s	remaining: 28.9s
89:	learn: 0.0563847	total: 2.85s	remaining: 28.8s
90:	learn: 0.0563798	total: 2.88s	remaining: 28.8s
91:	learn: 0.0563782	total: 2.92s	remaining: 28.8s
92:	learn: 0.0563745	total: 2.95s	remaining: 28.7s
93:	learn: 0.0563711	total: 2.98s	remaining: 28.7s
94:	learn: 0.0563684	total: 3.01s	remaining: 28.6s
95:	learn: 0.0563649	total: 3.04s	remaining: 28.6s
96:	learn: 0.0563631	total: 3.07s	remaining: 28.6s
97:	learn: 0.0563606	total: 3.09s	remaining: 28.5s
98:	learn: 0.0563581	total: 3.12s	remaining: 28.4s
99:	learn: 0.0563552	total: 3.15s	remaining: 28.4s
100:	learn: 0.0563535	total: 3.18s	remaining: 28.3s
101:	learn: 0.0563513	total: 3.21s	remaining: 28.2s
102:	learn: 0.0563467	total: 3.24s	remaining: 28.2s
103:	learn: 0.0563432	total: 3.27s	remaining: 28.2s
104:	learn: 0.0563388	total: 3.3s	remaining: 28.1s
105:	learn: 0.0563349	total: 3.33s	remaining: 28.1s
106:	learn: 0.0563325	total: 3.36s	remaining: 28s
107:	learn: 0.0563292	total: 3.39s	remaining: 28s
108:	learn: 0.0563269	total: 3.42s	remaining: 27.9s
109:	learn: 0.0563252	total: 3.45s	remaining: 27.9s
110:	learn: 0.0563227	total: 3.48s	remaining: 27.9s
111:	learn: 0.0563196	total: 3.51s	remaining: 27.8s
112:	learn: 0.0563173	total: 3.54s	remaining: 27.8s
113:	learn: 0.0563131	total: 3.57s	remaining: 27.7s
114:	learn: 0.0563111	total: 3.6s	remaining: 27.7s
115:	learn: 0.0563080	total: 3.63s	remaining: 27.7s
116:	learn: 0.0563046	total: 3.67s	remaining: 27.7s
117:	learn: 0.0563011	total: 3.69s	remaining: 27.6s
118:	learn: 0.0562980	total: 3.73s	remaining: 27.6s
119:	learn: 0.0562961	total: 3.75s	remaining: 27.5s
120:	learn: 0.0562942	total: 3.78s	remaining: 27.5s
121:	learn: 0.0562917	total: 3.81s	remaining: 27.4s
122:	learn: 0.0562891	total: 3.84s	remaining: 27.4s
123:	learn: 0.0562860	total: 3.87s	remaining: 27.3s
124:	learn: 0.0562841	total: 3.9s	remaining: 27.3s
125:	learn: 0.0562818	total: 3.94s	remaining: 27.3s
126:	learn: 0.0562793	total: 3.96s	remaining: 27.3s
127:	learn: 0.0562770	total: 4s	remaining: 27.2s
128:	learn: 0.0562747	total: 4.02s	remaining: 27.2s
129:	learn: 0.0562731	total: 4.05s	remaining: 27.1s
130:	learn: 0.0562711	total: 4.08s	remaining: 27.1s
131:	learn: 0.0562677	total: 4.11s	remaining: 27s
132:	learn: 0.0562639	total: 4.14s	remaining: 27s
133:	learn: 0.0562610	total: 4.17s	remaining: 27s
134:	learn: 0.0562577	total: 4.2s	remaining: 26.9s
135:	learn: 0.0562532	total: 4.24s	remaining: 26.9s
136:	learn: 0.0562514	total: 4.26s	remaining: 26.9s
137:	learn: 0.0562492	total: 4.29s	remaining: 26.8s
138:	learn: 0.0562470	total: 4.33s	remaining: 26.8s
139:	learn: 0.0562453	total: 4.35s	remaining: 26.7s
140:	learn: 0.0562439	total: 4.38s	remaining: 26.7s
141:	learn: 0.0562411	total: 4.41s	remaining: 26.7s
142:	learn: 0.0562395	total: 4.44s	remaining: 26.6s
143:	learn: 0.0562370	total: 4.47s	remaining: 26.6s
144:	learn: 0.0562361	total: 4.5s	remaining: 26.5s
145:	learn: 0.0562335	total: 4.53s	remaining: 26.5s
146:	learn: 0.0562312	total: 4.56s	remaining: 26.5s
147:	learn: 0.0562296	total: 4.59s	remaining: 26.4s
148:	learn: 0.0562281	total: 4.62s	remaining: 26.4s
149:	learn: 0.0562266	total: 4.65s	remaining: 26.3s
150:	learn: 0.0562244	total: 4.68s	remaining: 26.3s
151:	learn: 0.0562231	total: 4.71s	remaining: 26.3s
152:	learn: 0.0562186	total: 4.75s	remaining: 26.3s
153:	learn: 0.0562153	total: 4.79s	remaining: 26.3s
154:	learn: 0.0562124	total: 4.82s	remaining: 26.3s
155:	learn: 0.0562108	total: 4.87s	remaining: 26.3s
156:	learn: 0.0562093	total: 4.91s	remaining: 26.4s
157:	learn: 0.0562085	total: 4.95s	remaining: 26.4s
158:	learn: 0.0562050	total: 4.98s	remaining: 26.4s
159:	learn: 0.0562037	total: 5.01s	remaining: 26.3s
160:	learn: 0.0562028	total: 5.04s	remaining: 26.3s
161:	learn: 0.0561999	total: 5.07s	remaining: 26.2s
162:	learn: 0.0561987	total: 5.1s	remaining: 26.2s
163:	learn: 0.0561971	total: 5.13s	remaining: 26.1s
164:	learn: 0.0561959	total: 5.16s	remaining: 26.1s
165:	learn: 0.0561947	total: 5.19s	remaining: 26.1s
166:	learn: 0.0561921	total: 5.22s	remaining: 26s
167:	learn: 0.0561900	total: 5.25s	remaining: 26s
168:	learn: 0.0561884	total: 5.28s	remaining: 25.9s
169:	learn: 0.0561864	total: 5.31s	remaining: 25.9s
170:	learn: 0.0561854	total: 5.33s	remaining: 25.9s
171:	learn: 0.0561832	total: 5.36s	remaining: 25.8s
172:	learn: 0.0561816	total: 5.39s	remaining: 25.8s
173:	learn: 0.0561800	total: 5.42s	remaining: 25.7s
174:	learn: 0.0561786	total: 5.47s	remaining: 25.8s
175:	learn: 0.0561768	total: 5.52s	remaining: 25.8s
176:	learn: 0.0561752	total: 5.61s	remaining: 26.1s
177:	learn: 0.0561732	total: 5.65s	remaining: 26.1s
178:	learn: 0.0561713	total: 5.68s	remaining: 26s
179:	learn: 0.0561695	total: 5.71s	remaining: 26s
180:	learn: 0.0561680	total: 5.74s	remaining: 25.9s
181:	learn: 0.0561670	total: 5.77s	remaining: 26s
182:	learn: 0.0561644	total: 5.81s	remaining: 25.9s
183:	learn: 0.0561634	total: 5.84s	remaining: 25.9s
184:	learn: 0.0561625	total: 5.88s	remaining: 25.9s
185:	learn: 0.0561594	total: 5.91s	remaining: 25.9s
186:	learn: 0.0561582	total: 5.95s	remaining: 25.8s
187:	learn: 0.0561570	total: 5.98s	remaining: 25.8s
188:	learn: 0.0561549	total: 6.01s	remaining: 25.8s
189:	learn: 0.0561530	total: 6.04s	remaining: 25.7s
190:	learn: 0.0561518	total: 6.07s	remaining: 25.7s
191:	learn: 0.0561498	total: 6.1s	remaining: 25.7s
192:	learn: 0.0561490	total: 6.14s	remaining: 25.7s
193:	learn: 0.0561468	total: 6.17s	remaining: 25.6s
194:	learn: 0.0561460	total: 6.21s	remaining: 25.6s
195:	learn: 0.0561443	total: 6.24s	remaining: 25.6s
196:	learn: 0.0561428	total: 6.27s	remaining: 25.6s
197:	learn: 0.0561417	total: 6.3s	remaining: 25.5s
198:	learn: 0.0561406	total: 6.33s	remaining: 25.5s
199:	learn: 0.0561394	total: 6.36s	remaining: 25.4s
200:	learn: 0.0561378	total: 6.39s	remaining: 25.4s
201:	learn: 0.0561365	total: 6.42s	remaining: 25.4s
202:	learn: 0.0561354	total: 6.46s	remaining: 25.4s
203:	learn: 0.0561344	total: 6.49s	remaining: 25.3s
204:	learn: 0.0561327	total: 6.52s	remaining: 25.3s
205:	learn: 0.0561312	total: 6.56s	remaining: 25.3s
206:	learn: 0.0561302	total: 6.59s	remaining: 25.2s
207:	learn: 0.0561293	total: 6.62s	remaining: 25.2s
208:	learn: 0.0561271	total: 6.65s	remaining: 25.2s
209:	learn: 0.0561251	total: 6.68s	remaining: 25.1s
210:	learn: 0.0561241	total: 6.71s	remaining: 25.1s
211:	learn: 0.0561224	total: 6.75s	remaining: 25.1s
212:	learn: 0.0561202	total: 6.78s	remaining: 25s
213:	learn: 0.0561190	total: 6.81s	remaining: 25s
214:	learn: 0.0561169	total: 6.84s	remaining: 25s
215:	learn: 0.0561145	total: 6.87s	remaining: 24.9s
216:	learn: 0.0561129	total: 6.9s	remaining: 24.9s
217:	learn: 0.0561123	total: 6.93s	remaining: 24.9s
218:	learn: 0.0561106	total: 6.97s	remaining: 24.9s
219:	learn: 0.0561096	total: 7s	remaining: 24.8s
220:	learn: 0.0561087	total: 7.03s	remaining: 24.8s
221:	learn: 0.0561066	total: 7.06s	remaining: 24.7s
222:	learn: 0.0561056	total: 7.1s	remaining: 24.7s
223:	learn: 0.0561040	total: 7.14s	remaining: 24.7s
224:	learn: 0.0561019	total: 7.17s	remaining: 24.7s
225:	learn: 0.0561007	total: 7.21s	remaining: 24.7s
226:	learn: 0.0561000	total: 7.24s	remaining: 24.6s
227:	learn: 0.0560983	total: 7.27s	remaining: 24.6s
228:	learn: 0.0560974	total: 7.3s	remaining: 24.6s
229:	learn: 0.0560954	total: 7.33s	remaining: 24.5s
230:	learn: 0.0560926	total: 7.36s	remaining: 24.5s
231:	learn: 0.0560916	total: 7.39s	remaining: 24.5s
232:	learn: 0.0560902	total: 7.42s	remaining: 24.4s
233:	learn: 0.0560892	total: 7.45s	remaining: 24.4s
234:	learn: 0.0560876	total: 7.48s	remaining: 24.4s
235:	learn: 0.0560871	total: 7.52s	remaining: 24.3s
236:	learn: 0.0560864	total: 7.55s	remaining: 24.3s
237:	learn: 0.0560858	total: 7.57s	remaining: 24.3s
238:	learn: 0.0560849	total: 7.61s	remaining: 24.2s
239:	learn: 0.0560834	total: 7.63s	remaining: 24.2s
240:	learn: 0.0560820	total: 7.66s	remaining: 24.1s
241:	learn: 0.0560807	total: 7.69s	remaining: 24.1s
242:	learn: 0.0560795	total: 7.8s	remaining: 24.3s
243:	learn: 0.0560785	total: 7.83s	remaining: 24.2s
244:	learn: 0.0560774	total: 7.85s	remaining: 24.2s
245:	learn: 0.0560755	total: 7.88s	remaining: 24.2s
246:	learn: 0.0560745	total: 7.91s	remaining: 24.1s
247:	learn: 0.0560737	total: 7.94s	remaining: 24.1s
248:	learn: 0.0560725	total: 7.97s	remaining: 24s
249:	learn: 0.0560713	total: 8s	remaining: 24s
250:	learn: 0.0560699	total: 8.03s	remaining: 24s
251:	learn: 0.0560681	total: 8.06s	remaining: 23.9s
252:	learn: 0.0560675	total: 8.09s	remaining: 23.9s
253:	learn: 0.0560666	total: 8.12s	remaining: 23.8s
254:	learn: 0.0560659	total: 8.15s	remaining: 23.8s
255:	learn: 0.0560646	total: 8.18s	remaining: 23.8s
256:	learn: 0.0560626	total: 8.21s	remaining: 23.7s
257:	learn: 0.0560616	total: 8.25s	remaining: 23.7s
258:	learn: 0.0560606	total: 8.28s	remaining: 23.7s
259:	learn: 0.0560600	total: 8.3s	remaining: 23.6s
260:	learn: 0.0560593	total: 8.33s	remaining: 23.6s
261:	learn: 0.0560559	total: 8.36s	remaining: 23.5s
262:	learn: 0.0560548	total: 8.39s	remaining: 23.5s
263:	learn: 0.0560540	total: 8.42s	remaining: 23.5s
264:	learn: 0.0560533	total: 8.45s	remaining: 23.4s
265:	learn: 0.0560525	total: 8.48s	remaining: 23.4s
266:	learn: 0.0560515	total: 8.51s	remaining: 23.4s
267:	learn: 0.0560509	total: 8.54s	remaining: 23.3s
268:	learn: 0.0560501	total: 8.57s	remaining: 23.3s
269:	learn: 0.0560486	total: 8.6s	remaining: 23.2s
270:	learn: 0.0560473	total: 8.63s	remaining: 23.2s
271:	learn: 0.0560461	total: 8.66s	remaining: 23.2s
272:	learn: 0.0560455	total: 8.69s	remaining: 23.1s
273:	learn: 0.0560432	total: 8.71s	remaining: 23.1s
274:	learn: 0.0560425	total: 8.74s	remaining: 23.1s
275:	learn: 0.0560416	total: 8.77s	remaining: 23s
276:	learn: 0.0560408	total: 8.8s	remaining: 23s
277:	learn: 0.0560399	total: 8.84s	remaining: 22.9s
278:	learn: 0.0560393	total: 8.86s	remaining: 22.9s
279:	learn: 0.0560380	total: 8.89s	remaining: 22.9s
280:	learn: 0.0560361	total: 8.92s	remaining: 22.8s
281:	learn: 0.0560354	total: 8.95s	remaining: 22.8s
282:	learn: 0.0560348	total: 8.98s	remaining: 22.8s
283:	learn: 0.0560339	total: 9.01s	remaining: 22.7s
284:	learn: 0.0560329	total: 9.04s	remaining: 22.7s
285:	learn: 0.0560308	total: 9.07s	remaining: 22.7s
286:	learn: 0.0560297	total: 9.11s	remaining: 22.6s
287:	learn: 0.0560279	total: 9.14s	remaining: 22.6s
288:	learn: 0.0560267	total: 9.18s	remaining: 22.6s
289:	learn: 0.0560257	total: 9.21s	remaining: 22.6s
290:	learn: 0.0560249	total: 9.24s	remaining: 22.5s
291:	learn: 0.0560237	total: 9.27s	remaining: 22.5s
292:	learn: 0.0560225	total: 9.3s	remaining: 22.4s
293:	learn: 0.0560196	total: 9.33s	remaining: 22.4s
294:	learn: 0.0560180	total: 9.36s	remaining: 22.4s
295:	learn: 0.0560173	total: 9.39s	remaining: 22.3s
296:	learn: 0.0560143	total: 9.42s	remaining: 22.3s
297:	learn: 0.0560124	total: 9.45s	remaining: 22.3s
298:	learn: 0.0560117	total: 9.48s	remaining: 22.2s
299:	learn: 0.0560105	total: 9.51s	remaining: 22.2s
300:	learn: 0.0560093	total: 9.54s	remaining: 22.2s
301:	learn: 0.0560078	total: 9.57s	remaining: 22.1s
302:	learn: 0.0560069	total: 9.6s	remaining: 22.1s
303:	learn: 0.0560063	total: 9.63s	remaining: 22s
304:	learn: 0.0560045	total: 9.66s	remaining: 22s
305:	learn: 0.0560023	total: 9.69s	remaining: 22s
306:	learn: 0.0560014	total: 9.71s	remaining: 21.9s
307:	learn: 0.0560007	total: 9.74s	remaining: 21.9s
308:	learn: 0.0559993	total: 9.77s	remaining: 21.9s
309:	learn: 0.0559983	total: 9.8s	remaining: 21.8s
310:	learn: 0.0559971	total: 9.83s	remaining: 21.8s
311:	learn: 0.0559962	total: 9.86s	remaining: 21.7s
312:	learn: 0.0559944	total: 9.89s	remaining: 21.7s
313:	learn: 0.0559938	total: 9.92s	remaining: 21.7s
314:	learn: 0.0559928	total: 9.95s	remaining: 21.6s
315:	learn: 0.0559921	total: 9.98s	remaining: 21.6s
316:	learn: 0.0559909	total: 10s	remaining: 21.6s
317:	learn: 0.0559887	total: 10s	remaining: 21.5s
318:	learn: 0.0559876	total: 10.1s	remaining: 21.5s
319:	learn: 0.0559868	total: 10.1s	remaining: 21.4s
320:	learn: 0.0559860	total: 10.1s	remaining: 21.4s
321:	learn: 0.0559856	total: 10.2s	remaining: 21.4s
322:	learn: 0.0559851	total: 10.2s	remaining: 21.3s
323:	learn: 0.0559843	total: 10.2s	remaining: 21.3s
324:	learn: 0.0559836	total: 10.2s	remaining: 21.3s
325:	learn: 0.0559828	total: 10.3s	remaining: 21.2s
326:	learn: 0.0559816	total: 10.3s	remaining: 21.2s
327:	learn: 0.0559807	total: 10.3s	remaining: 21.2s
328:	learn: 0.0559799	total: 10.4s	remaining: 21.1s
329:	learn: 0.0559789	total: 10.4s	remaining: 21.1s
330:	learn: 0.0559779	total: 10.4s	remaining: 21.1s
331:	learn: 0.0559773	total: 10.5s	remaining: 21s
332:	learn: 0.0559766	total: 10.5s	remaining: 21s
333:	learn: 0.0559749	total: 10.5s	remaining: 21s
334:	learn: 0.0559743	total: 10.5s	remaining: 20.9s
335:	learn: 0.0559738	total: 10.6s	remaining: 20.9s
336:	learn: 0.0559733	total: 10.6s	remaining: 20.8s
337:	learn: 0.0559725	total: 10.6s	remaining: 20.8s
338:	learn: 0.0559711	total: 10.7s	remaining: 20.8s
339:	learn: 0.0559704	total: 10.7s	remaining: 20.7s
340:	learn: 0.0559695	total: 10.7s	remaining: 20.7s
341:	learn: 0.0559687	total: 10.7s	remaining: 20.7s
342:	learn: 0.0559677	total: 10.8s	remaining: 20.6s
343:	learn: 0.0559667	total: 10.8s	remaining: 20.6s
344:	learn: 0.0559657	total: 10.8s	remaining: 20.6s
345:	learn: 0.0559647	total: 10.9s	remaining: 20.5s
346:	learn: 0.0559638	total: 10.9s	remaining: 20.5s
347:	learn: 0.0559634	total: 10.9s	remaining: 20.4s
348:	learn: 0.0559623	total: 10.9s	remaining: 20.4s
349:	learn: 0.0559617	total: 11s	remaining: 20.4s
350:	learn: 0.0559614	total: 11s	remaining: 20.3s
351:	learn: 0.0559602	total: 11s	remaining: 20.3s
352:	learn: 0.0559594	total: 11.1s	remaining: 20.3s
353:	learn: 0.0559589	total: 11.1s	remaining: 20.2s
354:	learn: 0.0559582	total: 11.1s	remaining: 20.2s
355:	learn: 0.0559571	total: 11.2s	remaining: 20.2s
356:	learn: 0.0559556	total: 11.2s	remaining: 20.1s
357:	learn: 0.0559547	total: 11.2s	remaining: 20.1s
358:	learn: 0.0559537	total: 11.2s	remaining: 20.1s
359:	learn: 0.0559508	total: 11.3s	remaining: 20s
360:	learn: 0.0559495	total: 11.3s	remaining: 20s
361:	learn: 0.0559487	total: 11.3s	remaining: 20s
362:	learn: 0.0559478	total: 11.4s	remaining: 20s
363:	learn: 0.0559453	total: 11.4s	remaining: 19.9s
364:	learn: 0.0559442	total: 11.4s	remaining: 19.9s
365:	learn: 0.0559434	total: 11.5s	remaining: 19.9s
366:	learn: 0.0559424	total: 11.5s	remaining: 19.8s
367:	learn: 0.0559416	total: 11.5s	remaining: 19.8s
368:	learn: 0.0559405	total: 11.6s	remaining: 19.8s
369:	learn: 0.0559395	total: 11.6s	remaining: 19.7s
370:	learn: 0.0559384	total: 11.6s	remaining: 19.7s
371:	learn: 0.0559379	total: 11.6s	remaining: 19.7s
372:	learn: 0.0559371	total: 11.7s	remaining: 19.6s
373:	learn: 0.0559362	total: 11.7s	remaining: 19.6s
374:	learn: 0.0559355	total: 11.7s	remaining: 19.6s
375:	learn: 0.0559350	total: 11.8s	remaining: 19.5s
376:	learn: 0.0559344	total: 11.8s	remaining: 19.5s
377:	learn: 0.0559336	total: 11.8s	remaining: 19.4s
378:	learn: 0.0559328	total: 11.8s	remaining: 19.4s
379:	learn: 0.0559319	total: 11.9s	remaining: 19.4s
380:	learn: 0.0559311	total: 11.9s	remaining: 19.3s
381:	learn: 0.0559303	total: 11.9s	remaining: 19.3s

In [17]:
models = {
    "Linear Regression" : LinearRegression(),
    "KNN Regressor" : KNeighborsRegressor(n_neighbors=5),
    "Decision Tree Regressor" : DecisionTreeRegressor(max_depth=5, random_state=42),
    "Random Forest Regressor" : RandomForestRegressor(n_estimators=100, random_state=42),
    "Gradient Boosting reg" : GradientBoostingRegressor(n_estimators=100, random_state=42),
    "XGBoost" : XGBRegressor(n_estimators=200,
            max_depth=4,
            learning_rate=0.1,
            subsample=0.8,
            random_state=42
    ),
    "CatBoost" : CatBoostRegressor(verbose=0)
}

results = {}

for name, model in models.items():
    if name == "KNN Regressor":
        model.fit(X_train_sc, y_train)
        y_pred = model.predict(X_val_sc)
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_val)

    rmse = np.sqrt(mean_squared_error(y_val, y_pred))
    r2 = r2_score(y_val, y_pred)
    results[name] = r2
    print(f"{name:<30} RMSE: {rmse:.4f}  R²: {r2:.4f}")

best_model_name = max(results, key=results.get)
print(f"Best Model Name : {best_model_name}")

Linear Regression              RMSE: 0.0735  R²: 0.8041
KNN Regressor                  RMSE: 0.0619  R²: 0.8610
Decision Tree Regressor        RMSE: 0.0641  R²: 0.8511
Random Forest Regressor        RMSE: 0.0634  R²: 0.8545
Gradient Boosting reg          RMSE: 0.0570  R²: 0.8823
XGBoost                        RMSE: 0.0565  R²: 0.8843
CatBoost                       RMSE: 0.0563  R²: 0.8854
Best Model Name : CatBoost

In [18]:
xgb_params = {
    "n_estimators" : [100, 200, 300, 400, 500],
    "max_depth" : [3,4,5,6],
    "learning_rate" : [0.01, 0.05, 0.1, 0.2],
    "subsample" : [0.6, 0.7, 0.8, 1.0],
    "colsample_bytree" : [0.6, 0.7, 0.8, 1.0]
}

xgb_search = RandomizedSearchCV(
    estimator=XGBRegressor(eval_metric="rmse", random_state=42),
    param_distributions=xgb_params,
    n_iter=30,
    scoring="r2",
    cv = 5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

xgb_search.fit(X_train, y_train)
print(f"Best XGB param : {xgb_search.best_params_}")
print(f"Best XGB R2 : {xgb_search.best_score_}")

Fitting 5 folds for each of 30 candidates, totalling 150 fits
Best XGB param : {'subsample': 0.7, 'n_estimators': 500, 'max_depth': 6, 'learning_rate': 0.05, 'colsample_bytree': 0.7}
Best XGB R2 : 0.8863504118096731

In [26]:
# Tuning the best model

tuned_model = XGBRegressor(
    n_estimators  = 500,     # try: 100, 200, 300
    max_depth     = 6,       # try: 3, 4, 5, 6
    learning_rate = 0.05,    # try: 0.01, 0.05, 0.1, 0.2
    subsample     = 0.7,
    colsample_bytree = 0.7,
    eval_metric="logloss",
    random_state=42
)

In [27]:
cv_scores = cross_val_score(tuned_model, X, y, cv=5,
                             scoring="r2")
print(f"Cross-val scores : {cv_scores}")
print(f"Mean CV score    : {cv_scores.mean():.4f} (+/- {cv_scores.std():.4f})")

Cross-val scores : [0.88518198 0.88744217 0.88571592 0.88550438 0.88713484]
Mean CV score    : 0.8862 (+/- 0.0009)

### **Retrain on Full Train Dataset and Test on Test Dataset**

In [28]:
tuned_model.fit(X, y)
test_predictions = tuned_model.predict(X_test)

In [29]:
if hasattr(tuned_model, "feature_importances_"):
    importance = pd.Series(tuned_model.feature_importances_, index=X.columns)
    importance = importance.sort_values(ascending=False).head(15)
    print("\nTop 15 important features:")
    print(importance)

Top 15 important features:
lighting_night            0.354530
speed_limit               0.218738
curvature                 0.122666
lighting_dim              0.089931
weather_clear             0.077928
lighting_daylight         0.062193
num_reported_accidents    0.034874
weather_rainy             0.018037
weather_foggy             0.017925
holiday                   0.001497
public_road               0.000891
road_type_urban           0.000321
road_type_highway         0.000241
road_type_rural           0.000226
dtype: float32